### ISSUE TITLE
Feature Request - Transaction History

### ISSUE THREAD

**Issue by fanaticalfishing** [GaloyMoney/blinkbtc#2]
Can you add a downloadable transaction history for accounting purposes, as in the Osmo wallet? In pdf or Excel or pdf format?
It is essential for some business for tax purposes.

**Comment by designsats** [comment]
There is CSV export. Whats needed is to add USD rate of each transaction at the time of receiving.

**Comment by nicolasburtey** [comment]
there is a duplicate issue already present here, closing this one
