### ISSUE TITLE
Feature Request - High onchain fee alert

### ISSUE THREAD

**Issue by designsats** [GaloyMoney/blinkbtc#3]
Blink needs an alert preventing users to mistakenly send a small onchain transaction it times of high onchain fees. 

**Trigger**: Popup would trigger if users scans or pastes onchain address, fills the amount (which is smaller than 2x of Economy fee) and presses **Continue**. Then they should be alerted and aknowledge they are sure to proceed. **Cancel** shoud be primary button - we assume this was a mistake. 

Upon pressing **Cancel** - user should be redirected to first step of send flow with empty destination field. 

Pressing **I am sure** would allow them to **Confirm** sending. 

![dark theme - high fee alert](https://github.com/GaloyMoney/blinkbtc/assets/17384787/6f148296-cb8a-4cac-8f1a-83e6ca1a86ad)

**Comment by nicolasburtey** [comment]
this has been done
